version: "3.9"

services:
    localstack:
        container_name: "${LOCALSTACK_DOCKER_NAME-helm-s3-localstack_main}"
        environment:
            - LOCALSTACK_DATA_DIR=${LOCALSTACK_DATA_DIR- }
            - LOCALSTACK_DEBUG=${LOCALSTACK_DEBUG- }
            - LOCALSTACK_DOCKER_HOST=unix:///var/run/docker.sock
            - LOCALSTACK_HOST_TMP_FOLDER=${TMPDIR:-/tmp/localstack}
            - LOCALSTACK_KINESIS_ERROR_PROBABILITY=${LOCALSTACK_KINESIS_ERROR_PROBABILITY- }
            - LOCALSTACK_LAMBDA_EXECUTOR=${LOCALSTACK_LAMBDA_EXECUTOR- }
            - LOCALSTACK_PORT_WEB_UI=${LOCALSTACK_PORT_WEB_UI- }
            - LOCALSTACK_SERVICES=${LOCALSTACK_SERVICES- }
        image: localstack/localstack:0.12.10
        network_mode: bridge
        ports:
            - "${LOCALSTACK_PORT_WEB_UI-8080}:${LOCALSTACK_PORT_WEB_UI-8080}"
            - "4566:4566"
            - "4571:4571"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
