name: CI

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"
  schedule:
    - cron: "0 9 * * *"

# Note: currently jobs.<job-id>.(runs-on|strategy) cannot use '${{ env }}'.
# Until this is fixed, I'm moving static environment configuration into the
# configure-environment job's outputs (originally it handled dynamically
# determined values only).
#
# env:

jobs:
  configure-environment:
    name: Configure environment
    runs-on: ubuntu-latest # Note: OS independent job. # TODO: until static global env can be used through ${{ env }}.
    outputs:
      git-default-branch: origin/main
      git-refname: ${{ steps.set-git-refname.outputs.git-refname }}
      github-api-host: https://api.github.com
      github-api-version: "3"
      github-organization: banzaicloud
      github-repository: helm-s3
      github-runner-default-os: ubuntu-latest # Note: used for OS-independent jobs.
      github-runner-oses-json: '["ubuntu-latest"]'
      go-v1-version: ${{ steps.set-go-v1-version.outputs.go-v1-version }}
      goflags: -mod=readonly
      golangci-lint-v1-version: ${{ steps.set-golangci-lint-v1-version.outputs.golangci-lint-v1-version }}
      helm-v2-version: ${{ steps.set-helm-v2-version.outputs.helm-v2-version }}
      helm-v3-version: ${{ steps.set-helm-v3-version.outputs.helm-v3-version }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set Git refname
        id: set-git-refname
        run: echo ::set-output name=git-refname::$(echo "${{ github.ref }}" | sed -E 's@refs/(heads|pull|tags)/@@g')

      - name: Set Go v1 version
        id: set-go-v1-version
        run: echo ::set-output name=go-v1-version::$(make get-go-versions-json | jq --raw-output '. | map(select(startswith("1."))) | last')

      - name: Set golangci-lint v1 version
        id: set-golangci-lint-v1-version
        run: echo ::set-output name=golangci-lint-v1-version::$(make get-golangci-lint-versions-json | jq --raw-output '. | map(select(startswith("1."))) | last')

      - name: Set Helm v2 version
        id: set-helm-v2-version
        run: echo ::set-output name=helm-v2-version::$(make get-helm-versions-json | jq --raw-output '. | map(select(startswith("2."))) | last')

      - name: Set Helm v3 version
        id: set-helm-v3-version
        run: echo ::set-output name=helm-v3-version::$(make get-helm-versions-json | jq --raw-output '. | map(select(startswith("3."))) | last')

  check-git:
    name: Check Git constraints
    if: ${{ github.event_name != 'schedule' }}
    needs:
      - configure-environment
    runs-on: ${{ needs.configure-environment.outputs.github-runner-default-os }} # Note: OS independent job.
    steps:
      - name: Check unnecessary (rebase-removable) auto-generated merge commits
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: ^(?!Merge (branch '[^']+' into |pull request \#[1-9][0-9]* from ))(.*)$ # https://regex101.com/r/9CYsBr/1
          error: There is an auto-generated merge commit on the branch/pull request which is unnecessary noise and should be removed by rebasing the branch.
          excludeDescription: "true" # Note: we don't care about the PR description, only care about the automatic short message.
          excludeTitle: "true" # Note: we don't care about the PR title, only care about the automatic short message.
          checkAllCommitMessages: "true" # Note: all commit messages should be checked for a PR to prevent merging.
          accessToken: ${{ secrets.GITHUB_TOKEN }} # Note: required to check older commit messages.

  analyze-code:
    name: Analyze code
    needs:
      - configure-environment
    runs-on: ${{ needs.configure-environment.outputs.github-runner-default-os }} # Note: OS independent job.
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v${{ needs.configure-environment.outputs.golangci-lint-v1-version }}
          args: --new-from-rev ${{ needs.configure-environment.outputs.git-default-branch }} --timeout 10m

  build:
    name: Build project binaries and libraries
    needs:
      - configure-environment
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ${{ fromJSON(needs.configure-environment.outputs.github-runner-oses-json) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.configure-environment.outputs.go-v1-version }}

      - name: Cache Go module dependencies
        id: cache-go-module-dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: go-mod-cache-${{ runner.os }}-${{ needs.configure-environment.outputs.go-v1-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-cache-${{ runner.os }}-${{ needs.configure-environment.outputs.go-v1-version }}
            go-mod-cache-${{ runner.os }}
            go-mod-cache

      - name: Check Go modules dependency file integrity
        run: make check-go-mod-integrity

      - name: Build project binaries
        run: make build

      - name: Upload project binaries artifact
        uses: actions/upload-artifact@v2
        with:
          name: go-bins-${{ runner.os }}-${{ needs.configure-environment.outputs.go-v1-version }}
          path: bin
          if-no-files-found: error
          retention-days: 1

  test-unit:
    name: Run unit tests
    needs:
      - configure-environment
      - build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ${{ fromJSON(needs.configure-environment.outputs.github-runner-oses-json) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.configure-environment.outputs.go-v1-version }}

      - name: Cache Go module dependencies
        id: cache-go-module-dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: go-mod-cache-${{ runner.os }}-${{ needs.configure-environment.outputs.go-v1-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-cache-${{ runner.os }}-${{ needs.configure-environment.outputs.go-v1-version }}
            go-mod-cache-${{ runner.os }}
            go-mod-cache

      - name: Test (unit)
        run: make test-unit

  check-test-coverage-change:
    name: Check test coverage change
    needs:
      - configure-environment
      - build
    runs-on: ${{ needs.configure-environment.outputs.github-runner-default-os }} # Note: OS independent job.
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.configure-environment.outputs.go-v1-version }}

      - name: Cache Go module dependencies
        id: cache-go-module-dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: go-mod-cache-${{ runner.os }}-${{ needs.configure-environment.outputs.go-v1-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-cache-${{ runner.os }}-${{ needs.configure-environment.outputs.go-v1-version }}
            go-mod-cache-${{ runner.os }}
            go-mod-cache

      - name: Check test coverage integrity
        run: |
          current_test_coverage=$(make test-coverage)

          git checkout ${{ needs.configure-environment.outputs.git-default-branch }}
          default_test_coverage=$(make test-coverage|| echo "{}")

          jq --argjson CURRENT_TEST_COVERAGE "${current_test_coverage}" --argjson DEFAULT_TEST_COVERAGE "${default_test_coverage}" --exit-status --null-input \
            '$CURRENT_TEST_COVERAGE | keys | all(. as $key | ($DEFAULT_TEST_COVERAGE[$key] // 0.0) <= $CURRENT_TEST_COVERAGE[$key])' >/dev/null || \
            ( \
              printf >&2 '%s test coverage decreased compared to %s (default branch) test coverage\n%s (default branch) test coverage: %s\n%s test coverage: %s\n\n' \
                "${{ needs.configure-environment.outputs.git-refname }}" "${{ needs.configure-environment.outputs.git-default-branch }}" \
                "${{ needs.configure-environment.outputs.git-default-branch }}" "${default_test_coverage}" \
                "${{ needs.configure-environment.outputs.git-refname }}" "${current_test_coverage}" ; \
              exit 1 ; \
            )

  test-e2e:
    name: Run end to end tests
    needs:
      - configure-environment
      - build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ${{ fromJSON(needs.configure-environment.outputs.github-runner-oses-json) }}
        helm-major-version: # Note: because check names are bound to matrix values and floating versions require a lot of maintenance to keep them required checks on PRs to the default branch.
          - helmv2
          - helmv3
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ needs.configure-environment.outputs.go-v1-version }}

      - name: Set Helm version
        id: set-helm-version
        run: |
          case "${{ matrix.helm-major-version }}" in
          helmv2)
            echo ::set-output name=helm-version::${{ needs.configure-environment.outputs.helm-v2-version }}
            ;;
          helmv3)
            echo ::set-output name=helm-version::${{ needs.configure-environment.outputs.helm-v3-version }}
            ;;
          *)
            printf >&2 "unsupported Helm major version: %s\n" "${{ matrix.helm-major-version }}"

            exit 1
            ;;
          esac

      - name: Setup Helm
        run: |
          architecture=$(uname -m)
          case "${architecture}" in
          aarch64_be | aarch64 | armv6l | armv7l | armv8b | armv8l)
            architecture=arm64
            ;;
          x86_64)
            architecture=amd64
            ;;
          *)
            printf >&2 "unsupported architecture: %s\n" "${architecture}"

            exit 1
            ;;
          esac

          kernel_name=$(uname -s | tr "[:upper:]" "[:lower:]")
          helm_archive_name="helm-v${{ steps.set-helm-version.outputs.helm-version }}-${kernel_name}-${architecture}.tar.gz"
          echo "${helm_archive_name}"

          curl -sSL https://get.helm.sh/${helm_archive_name} -o ./${helm_archive_name}
          mkdir -p bin
          tar -xzf ${helm_archive_name} -C bin
          echo "${{ github.workspace }}/bin/${kernel_name}-${architecture}" >> $GITHUB_PATH

      - name: Initialize Helm v2 (required for plugin install before end to end test)
        if: endsWith(matrix.helm-major-version, 'v2')
        run: helm init --client-only

      - name: Cache Go module dependencies
        id: cache-go-module-dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: go-mod-cache-${{ runner.os }}-${{ needs.configure-environment.outputs.go-v1-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-cache-${{ runner.os }}-${{ needs.configure-environment.outputs.go-v1-version }}
            go-mod-cache-${{ runner.os }}
            go-mod-cache

      - name: Download project binaries artifact
        uses: actions/download-artifact@v2
        with:
          name: go-bins-${{ runner.os }}-${{ needs.configure-environment.outputs.go-v1-version }}
          path: bin

      - name: Set binary file permissions to executable
        run: chmod +x bin/helms3

      - name: Test (end to end)
        run: make test-e2e

  remove-temporary-artifacts:
    name: Remove temporary artifacts
    if: always()
    needs:
      - configure-environment
      - build
      - test-e2e
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ${{ fromJSON(needs.configure-environment.outputs.github-runner-oses-json) }} # Note: for OS specific artifacts.
    steps:
      - name: Remove project binaries artifact
        uses: geekyeggo/delete-artifact@v1
        if: ${{ needs.build.result }} == "success"
        with:
          name: go-bins-${{ runner.os }}-${{ needs.configure-environment.outputs.go-v1-version }}
